# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation in the root directory with Sphinx
#sphinx:
#  configuration: conf.py

# Optionally build your docs in additional formats such as PDF and EPUB
formats:
  - htmlzip
  - pdf

# Optionally specify a custom Python version
python:
  version: 3.8

# Optionally specify a custom build environment
build:
  image: latest

# Optionally specify a custom build command
#build:
#  command: make docs

# Optionally specify a custom requirements file
#python:
#  install:
#    - requirements.txt
